void main(){
  String firstName = "SM";
  String lastName ="Robin";
  print('${firstName} ${lastName}');
  
  
  double ricePrice=33;
  double eggPrice=10;
  double totalPrice=ricePrice+eggPrice;
  print('Total price is ${totalPrice.toStringAsFixed(2)}');
  
  int number1=39;
  int number2=19;
  int addition = number1+number2;
  print('${addition}');
  
  int subtraction=number1-number2;
  print('${subtraction}');
  
  
 int multipliction=number1*number2;
  print('${multipliction}');
  
  var division=number1/number2;
  print('${division.toStringAsFixed(2)}');
  
  
  
}
